services:
  Ttskch\PaginatorBundle\Config:
    properties:
      pageName: '%ttskch_paginator.page.name%'
      pageRange: '%ttskch_paginator.page.range%'
      limitName: '%ttskch_paginator.limit.name%'
      limitDefault: '%ttskch_paginator.limit.default%'
      sortKeyName: '%ttskch_paginator.sort.key.name%'
      sortDirectionName: '%ttskch_paginator.sort.direction.name%'
      sortDirectionDefault: '%ttskch_paginator.sort.direction.default%'
      templatePager: '%ttskch_paginator.template.pager%'
      templateSortable: '%ttskch_paginator.template.sortable%'

  Ttskch\PaginatorBundle\Paginator:
    arguments:
      - '@Ttskch\PaginatorBundle\Config'
      - '@form.factory'
      - '@request_stack'

  Ttskch\PaginatorBundle\Twig\TtskchPaginatorExtension:
    arguments:
      - '@Ttskch\PaginatorBundle\Config'
      - '@Ttskch\PaginatorBundle\Paginator'
      - '@twig'
    tags: {name: twig.extension}
