name: CI

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [8.0, 8.1, 8.2, 8.3]
        prefer-lowest: [false, true]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - uses: actions/checkout@v3

      - name: Get Composer cache directory path
        id: composer-cache-dir-path
        run: echo "path=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache-dir-path.outputs.path }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-

      - name: Install dependencies
        if: ${{ !matrix.prefer-lowest }}
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Install lowest dependencies
        if: ${{ matrix.prefer-lowest }}
        run: composer update -q --no-ansi --no-interaction --no-progress --prefer-dist --prefer-lowest

      - name: Execute tests
        if: ${{ !matrix.prefer-lowest }}
        run: composer tests

      - name: Execute tests for lowest dependencies
        if: ${{ matrix.prefer-lowest }}
        run: composer tests:bc
